trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'camilagbrito'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 
        $(Build.BuildId)
        latest

