trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/Tests.csproj'
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'camilagbrito48/projeto-rumos-camila'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'CamilaSubscription(b9793c71-6f87-40a9-833c-d79cb6c8ad35)'
    appType: 'webAppContainer'
    WebAppName: 'project78343-24-rumos'
    DockerNamespace: 'camilagbrito48'
    DockerRepository: 'projeto-rumos-camila'
    DockerImageTag: '$(Build.BuildId)'
