trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'camilagbrito'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      buildContext: '.'
      tags:
        $(Build.BuildId)
        latest